//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XULIA {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Cadenas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cadenas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XULIA.Cadenas", typeof(Cadenas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a neutro.
        /// </summary>
        internal static string cadena1 {
            get {
                return ResourceManager.GetString("cadena1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sobre.
        /// </summary>
        internal static string mnu_aboutToolStripMenuItem {
            get {
                return ResourceManager.GetString("mnu_aboutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda Xulia.
        /// </summary>
        internal static string mnu_ayudaXuliaToolStripMenuItem {
            get {
                return ResourceManager.GetString("mnu_ayudaXuliaToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Comandos.
        /// </summary>
        internal static string mnu_biscarComandosToolStripMenuItem {
            get {
                return ResourceManager.GetString("mnu_biscarComandosToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración XULIA.
        /// </summary>
        internal static string mnu_configuraciónXULIAToolStripMenuItem {
            get {
                return ResourceManager.GetString("mnu_configuraciónXULIAToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;SALIR.
        /// </summary>
        internal static string mnu_exitToolStripMenuItem {
            get {
                return ResourceManager.GetString("mnu_exitToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Archivo.
        /// </summary>
        internal static string mnu_fileToolStripMenuItem {
            get {
                return ResourceManager.GetString("mnu_fileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde Ficheros AIML.
        /// </summary>
        internal static string mnu_fromAIMLToolStripMenuItem {
            get {
                return ResourceManager.GetString("mnu_fromAIMLToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde Fichero DAT.
        /// </summary>
        internal static string mnu_fromDatFileToolStripMenuItem {
            get {
                return ResourceManager.GetString("mnu_fromDatFileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AIML por Defecto.
        /// </summary>
        internal static string mnu_fromDefaultToolStripMenuItem {
            get {
                return ResourceManager.GetString("mnu_fromDefaultToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A&amp;yuda.
        /// </summary>
        internal static string mnu_helpToolStripMenuItem {
            get {
                return ResourceManager.GetString("mnu_helpToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Última pregunta.
        /// </summary>
        internal static string mnu_lastRequestToolStripMenuItem {
            get {
                return ResourceManager.GetString("mnu_lastRequestToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Último resultado.
        /// </summary>
        internal static string mnu_lastResultToolStripMenuItem {
            get {
                return ResourceManager.GetString("mnu_lastResultToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Licencia.
        /// </summary>
        internal static string mnu_licenseToolStripMenuItem {
            get {
                return ResourceManager.GetString("mnu_licenseToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir Bot.
        /// </summary>
        internal static string mnu_newBotToolStripMenuItem {
            get {
                return ResourceManager.GetString("mnu_newBotToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recargar Configuración.
        /// </summary>
        internal static string mnu_recargarConfiguraciónToolStripMenuItem {
            get {
                return ResourceManager.GetString("mnu_recargarConfiguraciónToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Bot.
        /// </summary>
        internal static string mnu_saveBotToolStripMenuItem {
            get {
                return ResourceManager.GetString("mnu_saveBotToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        internal static string mnu_settingsToolStripMenuItem {
            get {
                return ResourceManager.GetString("mnu_settingsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fichero Simple.
        /// </summary>
        internal static string mnu_singleFileToolStripMenuItem {
            get {
                return ResourceManager.GetString("mnu_singleFileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string mnu_userToolStripMenuItem {
            get {
                return ResourceManager.GetString("mnu_userToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versiones.
        /// </summary>
        internal static string mnu_versionesToolStripMenuItem {
            get {
                return ResourceManager.GetString("mnu_versionesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        internal static string mnu_viewToolStripMenuItem {
            get {
                return ResourceManager.GetString("mnu_viewToolStripMenuItem", resourceCulture);
            }
        }
    }
}
